# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $
#
# #######################################################
# #### Configure recovery server - ("Linux/Windows") ####
# #######################################################

- name: "CONFIGURE-CRS -> Configure recovery server."
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
