# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

# NetBackup SERVER - START SERVICES
- name: NETBACKUP -> START SERVICES ("Linux")
  gather_facts: true
  become: yes
  hosts: all

  pre_tasks:
    - name: Retrieving host distribution
      setup:
        gather_subset:
          - "!all"
          - "!min"
          - "distribution"

    - name: "NBU-START-SERVICES -> Load configurable variables"
      ansible.builtin.include_vars: "vars/linux.yml"
      tags: ["always"]
      no_log: True

    - name: "NBU-START-SERVICES -> Input validation for netbackup role"
      fail:
        msg: "'nbu_role' is required to proceed with start services playbook. Do provide the NetBackup role and re-run the playbook."
      when:
      - nbu_role == ""

  roles:
    - role: 'netbackup'                        # Load netbackup common defaults
    - role: 'netbackup/posix'                  # Load netbackup default vars
    - role: 'generic/is_nbu_version_supported'
    - role: 'generic/nbu_compatibility'
    - role: 'netbackup/posix/nbu-start-services'
  vars:
    nbu_playbook_type: "startup"
    nbu_playbook_name: "nbu_start_services"
    nbu_role: ""                  # Supported values ['primary','media','client']
