# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

- name: "NBU-PARTIAL-INSTALL-DETECTION -> Setting facts for Windows"
  ansible.builtin.set_fact:
    nbap_partial_install_detected: false
    nbap_partial_role_detected: "{{ nbu_detected_role }}"
    nbap_previous_playbook_type: "{{ nbu_playbook_type }}"

#EOF