# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

# Check if base installation path exists
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Verify base installation path ({{ os_path_nbu_install_default }}) existence"
  ansible.builtin.stat:
    path: "{{ os_path_nbu_install_default }}"
  register: install_path_check_register

# Show various error messages
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Check base installation path ({{ os_path_nbu_install_default }}) status"
  block:
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Check link status of install path ({{ os_path_nbu_install_default }})"
      fail:
        msg: "In case of typical/default installation path ({{ os_path_nbu_install_default }}), it shouldn't be a link. We recommend to have the installation path removed and re-run the playbook."
      when:
        - os_path_nbu_install == os_path_nbu_install_default
        - install_path_check_register.stat.islnk

    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Check custom installation path ({{ os_path_nbu_install }}) status"
      fail:
        msg: "A custom installation path ({{ os_path_nbu_install }}) is provided, but ({{ os_path_nbu_install_default }}) is already linked to a different ({{ install_path_check_register.stat.lnk_source }}) path. We recommend you to remove the link and re-run the playbook."
      when:
        - os_path_nbu_install != os_path_nbu_install_default
        - install_path_check_register.stat.islnk
        - os_path_nbu_install != install_path_check_register.stat.lnk_source

    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Check directory status of install path ({{ os_path_nbu_install_default }})"
      fail:
        msg:  "In case of custom installation path ({{ os_path_nbu_install }}), '{{ os_path_nbu_install_default }}' shouldn't be a directory. We recommend you to remove '{{ os_path_nbu_install_default }}' and re-run the playbook."
      when:
        - os_path_nbu_install != os_path_nbu_install_default
        - not install_path_check_register.stat.islnk

    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Verify installation path for upgrade case"
      fail:
        msg: "NetBackup {{ nbu_role|capitalize }} ({{ nbu_server_rpm_version }}) is installed at ({{ install_path_check_register.stat.lnk_source }}). As this is an upgrade, different install path ({{ os_path_nbu_install }}) isn't allowed"
      when:
        - install_path_check_register.stat.islnk
        - os_path_nbu_install != install_path_check_register.stat.lnk_source
        - nbu_playbook_type == "upgrade"
  when:
    - install_path_check_register.stat.exists

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Symlink path creation"
  block:
    # Ensure the NetBackup install directory exists
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Ensure NetBackup {{ os_path_nbu_install }} directory exists"
      ansible.builtin.file:
        path: "{{ os_path_nbu_install }}"
        state: directory
        owner: "root"
        group: "bin"
        mode: "0755"

    # Ensure the NetBackup install directory link exists
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Ensure NetBackup {{ os_path_nbu_install }} -> {{ os_path_nbu_install_default }} link exists"
      ansible.builtin.file:
        src: "{{ os_path_nbu_install }}"
        dest: "{{ os_path_nbu_install_default }}"
        state: link
  when:
    - install_path_check_register.stat.exists == false
    - os_path_nbu_install != os_path_nbu_install_default

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Physical path creation"
  block:
    # Ensure the NetBackup install directory exists
    - name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Ensure NetBackup {{ os_path_nbu_install }} directory exists"
      ansible.builtin.file:
        path: "{{ os_path_nbu_install }}"
        state: directory
        owner: "root"
        group: "bin"
        mode: "0755"
  when:
    - install_path_check_register.stat.exists == false
    - os_path_nbu_install == os_path_nbu_install_default

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Create [{{ os_path_openv_tmp }}] directory if it does not exist"
  ansible.builtin.file:
    path: "{{ os_path_openv_tmp }}"
    state: directory

#EOF