# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

#############################################
#### NetBackup Remove ####
#############################################
# Import required tasks - Base Remove

# Import required tasks - Base Remove
- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Verify whether the NetBackup {{ nbu_role | capitalize }} is installed and is the version supported for removal by this Playbook"
  ansible.builtin.include_tasks: t01_pre_remove_check.yml

- name: "NBU-{{ nbu_role|upper }}-{{ nbu_playbook_type|upper }} -> Remove the NetBackup {{ nbu_role | capitalize }}"
  ansible.builtin.include_tasks: t03_base_remove.yml
  when: nbu_rpm_check_register.rc == 0

# EOF