# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $
#
# ############################################################
# #### Add vcenter to recovery server - ("Linux/Windows") ####
# ############################################################

- name: "ADD-VCENTER-TO-CRS -> Add vcenter to recovery server."
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
