# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $
#
# ##################################################
# #### Register CRS on alta - ("Linux/Windows") ####
# ##################################################

- name: "REGISTER-CRS-ON-ALTA -> Register CRS on Alta."
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
