# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $
#
# ###############################################################
# #### Import images for recovery server - ("Linux/Windows") ####
# ###############################################################

- name: "IMPORT-IMAGES -> Import images for recovery server."
  ansible.builtin.include_tasks: "{{ ansible_system|lower }}.yml"
