# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

# The install will not be performed if the playbook type is different from installed software on target host machine
# Verify whether the NetBackup software(Client/Media/Primary) is completely installed
- name: "NBU-ROLE-STATUS -> Verify the bpclntcmd file existence status"
  win_stat:
    path: "{{ os_path_nbu_install }}\\NetBackup\\bin\\bpclntcmd.exe"
  register: netbackup_bpclntcmd_file_register
  failed_when: false
  changed_when: false

- name: "NBU-ROLE-STATUS -> Check if target host machine is Primary/Media/Client"
  block: 
    - name: "NBU-ROLE-STATUS -> Get hostname of target host machine"
      win_command: "bpclntcmd.exe -gethostname"
      args:
        chdir: "{{ os_path_nbu_install }}\\NetBackup\\bin"
      changed_when: false
      register: nbu_get_hostname_register
      failed_when: false

    - name: "NBU-ROLE-STATUS -> Check if target host machine is Primary/Media/Client"
      block:
        - name: "NBU-ROLE-STATUS -> Check if target host machine is Primary Server "
          win_command: "bpclntcmd.exe {{ item }} {{ nbu_get_hostname_register.stdout }}"
          args:
            chdir: "{{ os_path_nbu_install }}\\NetBackup\\bin"
          register: nbu_is_master_media_register
          changed_when: false
          failed_when: false
          with_items:
            - "-is_master_server"
            - "-is_media_server"

        - name: "NBU-ROLE-STATUS -> Check if target host machine is Primary Server and Set NBU_Role to primary" 
          ansible.builtin.set_fact:
            nbu_detected_role: "primary"
          when:
            - ( nbu_is_master_media_register.results[0].rc == 0 )  
            - ( nbu_is_master_media_register.results[1].rc == 0 )

        - name: "NBU-ROLE-STATUS -> Check if target host machine is Media Server and set NBU_Role to media" 
          ansible.builtin.set_fact:
            nbu_detected_role: "media"
          when:
            - ( nbu_is_master_media_register.results[0].rc != 0 ) 
            - ( nbu_is_master_media_register.results[1].rc == 0 ) 

        - name: "NBU-ROLE-STATUS -> Check if target host machine is Client and set NBU_Role to client" 
          ansible.builtin.set_fact:
            nbu_detected_role: "client"
          when:
            - ( nbu_is_master_media_register.results[0].rc != 0 )
            - ( nbu_is_master_media_register.results[1].rc != 0 ) 

        - name: "NBU-ROLE-STATUS -> Set NBU_Role to ( nbu_detected_role ) if nbu_role is undefined" 
          ansible.builtin.set_fact:
            nbu_role: "{{ nbu_detected_role }}"
          when:
            - ( nbu_role is not defined )  
            
      when:
        - ( nbu_get_hostname_register.rc == 0 )
  when:
    - netbackup_bpclntcmd_file_register.stat.exists