# $Copyright: Copyright (c) 2025 Cohesity, Inc. All rights reserved $

nbap_ansible_system : "{{ 'win32nt' if 'Win32NT' in ansible_system else 'posix' }}"

# Ansible - OS family list
nbu_compatibility_matrix:
  - appversion: 11.1.0.0
    os_min_support:
      RedHat: 8.6
      Suse: 15
      AIX: 7.1
      Solaris: 11.0
      Windows: 6.2
  - appversion: 11.0.0.1
    os_min_support:
      RedHat: 8.6
      Suse: 15
      AIX: 7.1
      Solaris: 11.0
      Windows: 6.2
  - appversion: 11.0.0.0
    os_min_support:
      RedHat: 8.6
      Suse: 15
      AIX: 7.1
      Solaris: 11.0
      Windows: 6.2   
  - appversion: 10.5.0.1
    os_min_support:
      RedHat: 8.6
      Suse: 15
      AIX: 7.1
      Solaris: 11.0
      Windows: 6.2
  - appversion: 10.5.0.0
    os_min_support:
      RedHat: 8.6
      Suse: 15
      AIX: 7.1
      Solaris: 11.0
      Windows: 6.2
      
